apiVersion: v1
kind: Service
metadata:
  name: myspringbootapp
  namespace: default
spec:
  selector:
    app: myspringbootapp
  type: LoadBalancer
  ports:
    - nodePort: 30036
      port: 80
      targetPort: 9099